### ISSUE TITLE
Apply relevant ACCESS universal navigation and footer to identity.access-ci.org

### ISSUE THREAD

**Issue by jpnavarro** [cilogon/access-identity#31]
As of June 2023 the latest ACCESS universal navigation header and footer conventions are partially implemented on the identity.access-ci.org website. These conventions have changed since identity.access-ci.org navigation was first implemented. Suggest that we apply the latest ACCESS universal navigation header and footer to identity.access-ci.org as documented at: https://github.com/access-ci-org/Web_and_Branding

**Comment by jbasney** [comment]
When I added the ACCESS universal navigation for #22 I used the reference at https://github.com/qltd/access-universal-nav/blob/master/nav.html but it looks like that has not been updated since. What should I be using instead? At https://github.com/access-ci-org/Web_and_Branding I see some PDFs but no css or html that I can use directly.

Would it be possible for someone who understands the changes to provide a pull request?

**Comment by jpnavarro** [comment]
The web and branding team recently agreed to consolidate all our source material and design decisions into the new [https://github.com/access-ci-org/Web_and_Branding](https://github.com/access-ci-org/Web_and_Branding) repo.

This includes improvements to the universal navigation and footer that we've been working on over the last several months and are now listing in the README. That old "qltd" repo is no longer official or up-to-date.

There are multiple web frameworks in use, so we are leaving the implementation (including css or html) up to each website.

**Comment by jbasney** [comment]
fixed by #35
